version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: video_share_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./back-end
    restart: always
    ports:
      - '3001:3001'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: 123456
      DB_NAME: video_share_db
      SECRET_KEY: secretKey
    networks:
      - app-network

  frontend:
    build:
      context: ./front-end
      args:
        NEXT_PUBLIC_API_URL: http://backend:3001
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
    
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
